### ISSUE TITLE
Multiple Backup Folders creates still /data backup

### ISSUE THREAD

**Issue by chraebsli** [AdrienPoupa/rclone-backup#16]
When using the container `v1.0.3` (latest) with the multiple backup folders configured, it still generates a backup for the whole `/data` folder, although it shouldn't.

My config looks like this:
```yaml
services:
  backup:
    image: adrienpoupa/rclone-backup:latest
    environment:
      BACKUP_FOLDER_NAME:
      BACKUP_FOLDER_PATH: '.'
      BACKUP_FOLDER_NAME_1: 'Backup_1'
      BACKUP_FOLDER_PATH_1: '/data/backup1'
      BACKUP_FOLDER_NAME_2: 'Backup_2'
      BACKUP_FOLDER_PATH_2: '/data/backup2'
```

3 Backups are being generated:
- Backup_1: `/data/backup1`
- Backup_2: `/data/backup2`
- data: `/data`

It doesn't matter if the variables `BACKUP_FOLDER_NAME` & `BACKUP_FOLDER_PATH` are not set, empty or something other.
